services:
  - type: web
    name: playwright-captcha-aware
    env: node
    plan: free
    buildCommand: |
      npm ci
      npx playwright install --with-deps
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
